title: PuG 2026 Calendar
description: Add the PUG 2026 conference sessions directly to your Google Calendar.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub Pages settings
url: "https://caggursoy.github.io"
baseurl: "/pug26-calendar"

# Optional: link back to the GitHub repo
github:
  repository_url: "https://github.com/caggursoy/pug26-calendar"
